# Uncomment the next line to define a global platform for your project
  platform :ios, '15.5'

target 'Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diary
  pod 'dredfort2022', '~> 0.5.0'

end
